# Generated by Django 5.0.1 on 2024-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (0, 'female')])),
                ('chest_pain', models.IntegerField(blank=True, null=True)),
                ('resting_bp', models.IntegerField(blank=True, null=True)),
                ('cholestrol', models.IntegerField(blank=True, null=True)),
                ('fasting_blood_suger', models.IntegerField(blank=True, null=True)),
                ('resting_ecg', models.IntegerField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('exercise_angina', models.IntegerField(blank=True, null=True)),
                ('oldpeak', models.IntegerField(blank=True, null=True)),
                ('ST_slope', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
